const ERRORS = {
	'5003': 'falha de comunicação com a instituição financeira',
    '10000': 'bandeira inválida',
    '10001': "número do cartão inválido",
    '10002': "data no formato inválido",
    '10003': "código de segurança inválido",
    '10004': "cvv obrigatório",
    '10006': "código de segurança inválido",
    '53004': "quantidade de ítens inválido",
    '53005': "moeda obrigatória",
    '53006': "moeda inválida",
    '53007': "tamanho do campo referência inválido",
    '53008': "url de notificação inválida",
    '53009': "tamanho da url de notificação inválida",
    '53010': "email do comprador inválido.",
    '53011': "email do comprador inválido",
    '53012': "tamanho do campo email do comprador inválido",
    '53013': "nome do comprador obrigatório",
    '53014': "nome do comprador inválido",
    '53015': "tamanho do campo nome do comprador inválido",
    '53017': "cpf do comprador inválido",
    '53018': "código de área do telefone inválido",
    '53019': "tamanho do campo código de área do telefone inválido",
    '53020': "telefone obrigatório",
    '53021': "telefone inválido",
    '53022': "CEP obrigatório",
    '53023': "CEP inválido",
    '53024': "rua do endereço obrigatório",
    '53025': "rua do endereço inválido",
    '53026': "número do endereço obrigatório",
    '53027': "número do endereço inválido",
    '53028': "complemento do endereço inválido",
    '53029': "bairro do endereço obrigatório",
    '53030': "bairro do endereço inválido",
    '53031': "cidade do endereço obrigatória",
    '53032': "cidade do endereço inválida",
    '53033': "estado do endereço obrigatório",
    '53034': "estado do endereço inválido",
    '53035': "país do endereço obrigatório.",
    '53036': "país do endereço inválido",
    '53037': "token do cartão de crédito obrigatório",
    '53038': "quantidade de parcelas obrigatória",
    '53039': "quantidade de parcelas inválida",
    '53040': "valor da parcela obrigatória",
    '53041': "valor da parcela inválida",
    '53042': "portador do cartão obrigatório",
    '53043': "portador do cartão inválido",
    '53044': "tamanho do campo portador do cartão inválido",
    '53045': "CPF do portador do cartão obrigatório",
    '53046': "CPF do portador do cartão inválido",
    '53047': "data de nascimento do portador do cartão obrigatório",
    '53048': "data de nascimento do portador do cartão inválido",
    '53049': "código de área do portador do cartão obrigatório",
    '53050': "código de área do portador do cartão inválido",
    '53051': "telefone do portador do cartão obrigatório",
    '53052': "telefone  do portador do cartão inválido",
    '53053': "CEP do portador do cartão obrigatório",
    '53054': "CEP do portador do cartão inválido",
    '53055': "rua do portador do cartão obrigatório",
    '53056': "rua do portador do cartão inválido",
    '53057': "número do endereço do portador do cartão obrigatório",
    '53058': "número do endereço do portador do cartão inválido",
    '53059': "tamanho do campo complemento do endereço do portador do cartão inválido",
    '53060': "bairro do portador do cartão obrigatório",
    '53061': "tamanho do campo bairro do portador do cartão inválido",
    '53062': "cidade do portador do cartão obrigatório",
    '53063': "tamanho do campo cidade do portador do cartão inválido",
    '53064': "estado do portador do cartão obrigatório",
    '53065': "estado do portador do cartão inválido",
    '53066': "país do portador do cartão obrigatório",
    '53067': "tamanho do campo país do portador do cartão inválido",
    '53068': "tamanho do email do vendedor inválido",
    '53069': "email do vendedor inválido",
    '53070': "código do ítem obrigatório",
    '53071': "tamanho do código do ítem inválido",
    '53072': "descrição do ítem obrigatório",
    '53073': "tamanho do campo ítem inválido",
    '53074': "quantidade de ítens obrigatória",
    '53075': "quantidade de ítens fora do limite",
    '53076': "quantidade de ítens inválido",
    '53077': "montante do ítem obrigatório",
    '53078': "montante do ítem inválido.",
    '53079': "montante fora do limite",
    '53081': "comprador é igual ao vendedor",
    '53084': "vendedor inválido, verifique se é uma conta com status de vendedor",
    '53085': "método de pagamento indisponível",
    '53086': "montante total acima do limite do cartão",
    '53087': "dados do cartão inválidos",
    '53091': "hash do comprador inválido",
    '53092': "bandeira do cartão não aceita",
    '53095': "tipo de entrega inválido",
    '53096': "custo de entrega inválido",
    '53097': "custo da entrega fora do limite",
    '53098': "valor total é negatívo",
    '53099': "montante extra inválido.",
    '53101': "modo de pagamento inválido, valores válidos são default e gateway",
    '53102': "método de pagamento inválido, valores válidos são creditCard, boleto e eft",
    '53104': "custo de entrega informado, endereço de entrega deve ser completo",
    '53105': "informações do comprador informado, email também deve ser informado",
    '53106': "portador do cartão incompleto",
    '53109': "endereço do comprador informado, email do comprador também deve ser informado",
    '53110': "banco eft obrigatório",
    '53111': "banco eft não aceito",
    '53115': "data de nascimento do comprador inválida",
    '53117': "CPNJ do comprador inválido",
    '53122': "domínio do email do comprador inválido. Você deve usar um email @sandbox.pagseguro.com.br",
    '53140': "quantidade de parcelas fora do limite. O valor deve ser maior que zero",
    '53141': "comprador bloqueado",
    '53142': "token do cartão de crédito inválido",
    '14007': "status da transação não permite reembolso",
}

/**
* getError
* @param {String} code ex: 33231
* @param {String} defaultError ex: campo incorreto!
*/
export const getError = (code, defaultError = 'Erro na integração do Pagseguro') => {
	if (ERRORS.hasOwnProperty(code)) {
		return ERRORS[code];
	}

	return defaultError;
}
